const assert = require('assert');
const fs = require('fs');

const html = fs.readFileSync('index.html', 'utf8');
const main = fs.readFileSync('assets/main.js', 'utf8');

assert(html.includes('id="language-switch"'), 'UI should provide a language switch');
assert(html.includes('href="assets/style.css?v=20260526-1"'), 'home page should load CSS from assets/');
assert(html.includes('src="assets/main.js?v=20260526-1"'), 'home page should load main script from assets/');
assert(html.includes('class="top-bar"'), 'main page should use a separate top navigation bar');
assert(html.includes('portal-main-nav'), 'main page should use portal top navigation');
assert(html.includes('class="sub-nav-bar"'), 'main page should use a secondary navigation bar');
assert(html.includes('class="sub-nav"'), 'main page should expose primary-section child navigation');
assert(html.includes('data-i18n="sub.parser"'), 'home secondary navigation should be localizable');
assert(!html.includes('class="portal-menu"'), 'main page should not keep the removed common-entry menu');
assert(html.includes('data-i18n="portal.tools">解析工具</a>'), 'main navigation should consistently label the parser entry');
assert(html.includes('data-i18n="portal.tutorials"'), 'main navigation should expose the tutorials category');
assert(html.includes('href="pages/h264-guide.html"'), 'home page should link content pages through pages/');
assert(!html.includes('portal-categories'), 'main page should not keep the removed left category navigation');
assert(html.indexOf('class="top-bar"') < html.indexOf('<header class="site-header"'), 'top navigation should sit above the hero header');
assert(html.includes('data-i18n='), 'static UI text should be marked for localization');
assert(html.includes('data-i18n-html='), 'localized rich text should use explicit HTML translation markers');
assert(html.includes('data-i18n-placeholder='), 'localized inputs should support translated placeholders');
assert(html.includes('data-i18n-aria-label='), 'localized controls should support translated aria labels');
assert(main.includes('const I18N ='), 'main UI should define localization dictionaries');
assert(main.includes('let currentLanguage'), 'main UI should track selected language');
assert(main.includes('function t('), 'main UI should translate dynamic labels through t()');
assert(main.includes('function setLanguage('), 'UI should switch language without reloading');
assert(main.includes('localStorage'), 'language selection should persist in localStorage');
assert(main.includes('applyTranslations'), 'static localized text should be applied from JS');
assert(main.includes('translateWorkerError'), 'worker errors should be routed through localization');
assert(main.includes("new Worker('assets/parser-worker.js?v=20260526-1')"), 'parser worker should load from assets/');
assert(html.includes('什么是 H.264？'), 'SEO content should visibly explain what H.264 is');
assert(html.includes('什么是 H.265？'), 'SEO content should visibly explain what H.265 is');
assert(html.includes('"@type": "FAQPage"'), 'SEO content should include FAQPage structured data');
assert(html.includes('property="og:title"'), 'SEO metadata should include Open Graph title');
assert(html.includes('name="twitter:card"'), 'SEO metadata should include Twitter summary card');
assert(main.includes('tech.whatH264Title'), 'localized SEO content should include H.264 heading');
assert(main.includes('tech.whatH265Title'), 'localized SEO content should include H.265 heading');
assert(!main.includes('portal.ffmpegExtract'), 'common navigation should not keep a duplicate FFmpeg entry');
assert(main.includes('sub.parser'), 'localized UI should include the parser secondary navigation label');

const tidHeaderCount = (html.match(/class="tid-col" title="Temporal ID"><abbr title="Temporal ID">TID<\/abbr>/g) || []).length;
assert.strictEqual(tidHeaderCount, 2, 'NAL and frames tables should mark TID headers with a dedicated column class');
assert(html.includes('<th class="tid-col" title="Temporal ID"><abbr title="Temporal ID">TID</abbr></th>'), 'NAL table should mark TID header with a dedicated column class');
assert(main.includes('<td class="tid-col">'), 'NAL table should mark TID values with the same column class as the header');
assert(!html.includes('<colgroup>'), 'NAL table should not use colgroup for hidden codec columns');
assert(html.includes('id="nal-codec-header" class="codec-col"'), 'NAL table should have one codec-specific header');
assert(!html.includes('class="col-h264"'), 'NAL table should not keep a hidden H.264 column');
assert(!html.includes('class="col-h265"'), 'NAL table should not keep a hidden H.265 column');
assert(main.includes('nalCodecHeader.textContent'), 'NAL table should rename the single codec column per codec');
assert(main.includes('<td class="codec-col">'), 'NAL rows should render one codec-specific value column');
assert(html.indexOf('data-i18n="table.frame">Frame</th>') < html.indexOf('data-i18n="table.startCode">起始码</th>'), 'NAL table should show Frame before start code');
assert(main.indexOf('frame-pill') < main.indexOf('${startCodeType}</td>'), 'NAL rows should render Frame before start code');
assert(main.includes('getNALDisplayName'), 'NAL name cells should use compact display names');
assert(main.includes('title="${escapeHtml(nal.type_name)}"'), 'NAL name cells should keep the full name in a tooltip');
assert(main.includes('Showing bytes'), 'binary truncation note should explain that it is a preview window');
assert(main.includes('Showing all'), 'binary note should also explain when the full NAL is visible');
assert(main.includes('toLocaleString()'), 'binary truncation note should format large byte counts');
assert(main.includes('data-search-text'), 'NAL rows should carry normalized search text');
assert(main.includes('data-frame-type'), 'NAL rows should expose frame type for exact I/P/B filtering');
assert(main.includes('getFrameTypeSearchQuery'), 'NAL filter should special-case exact I/P/B frame type queries');
assert(main.includes('buildNALSearchText'), 'NAL search should be built from structured fields');
assert(main.includes('frame ${frameType.toLowerCase()}'), 'NAL search text should include frame I/P/B tokens');
assert(main.includes('frame-idr'), 'NAL frame pill should have a distinct IDR style');
assert(main.includes("frameType === 'IDR'"), 'NAL frame display should distinguish IDR from regular I frames');
assert(main.includes('idrFrames'), 'summary should render IDR counts separately');
assert(main.includes('field-clickable'), 'clickable field rows should have an explicit class');
assert(main.includes('field-static'), 'static field rows should have an explicit class');
assert(main.includes('buildNALFieldTree'), 'Selected NAL fields should be rendered from a tree model');
assert(main.includes('renderFieldTreeNode'), 'Selected NAL tree should render nested nodes');
assert(main.includes('field-tree-node'), 'Selected NAL tree should use collapsible node markup');
assert(main.includes('field-tree-toggle'), 'Selected NAL tree nodes should have an explicit toggle area');
assert(main.includes('field-tree-children'), 'Selected NAL tree should group nested child rows');
assert(main.includes('data-field-path'), 'clickable tree leaves should keep field paths for bit highlighting');
assert(main.includes('FLAG_GROUP_RULES'), 'Selected NAL tree should group conditional fields under their controlling flags');
assert(main.includes('groupConditionalFieldNodes'), 'Selected NAL tree should normalize flag-controlled subtrees');
assert(main.includes('SYNTHETIC_GROUP_RULES'), 'Selected NAL tree should provide synthetic syntax-section groups');
assert(main.includes('PPS Extension'), 'PPS extension fields should be grouped under an expandable PPS Extension node');
assert(main.includes('bitstream_restriction_flag'), 'VUI bitstream restriction fields should be grouped under bitstream_restriction_flag');
assert(main.includes('vui_timing_info_present_flag'), 'H.265 VUI timing fields should be grouped under vui_timing_info_present_flag');
assert(main.includes('vui_hrd_parameters_present_flag'), 'H.265 VUI HRD fields should be grouped under vui_hrd_parameters_present_flag');
assert(main.includes('vps_timing_info_present_flag'), 'H.265 VPS timing fields should be grouped under vps_timing_info_present_flag');
assert(main.includes('pps_extension_present_flag'), 'H.265 PPS extension fields should be grouped under pps_extension_present_flag');
assert(main.includes('sps_extension_present_flag'), 'H.265 SPS extension fields should be grouped under sps_extension_present_flag');
assert(main.includes('pps_scc_extension_flag'), 'H.265 PPS SCC extension fields should be grouped under pps_scc_extension_flag');
assert(main.includes('sps_scc_extension_flag'), 'H.265 SPS SCC extension fields should be grouped under sps_scc_extension_flag');
assert(main.includes('frame_cropping_flag'), 'SPS crop offsets should be grouped under frame_cropping_flag');
assert(main.includes('field-tree-toggle') && main.includes('data-field-path'), 'clickable tree group nodes should keep field paths for bit highlighting');
assert(main.includes('assignAggregateFieldRanges'), 'tree parent nodes should receive aggregate bit ranges from clickable children');
assert(!main.includes('node.range.coding'), 'aggregate field range creation must not dereference an empty node.range');
assert(main.includes('data-field-start-bit'), 'clickable field nodes should carry bit ranges in the DOM');
assert(main.includes('data-field-segments'), 'clickable field nodes should carry segmented bit ranges for H.265 emulation-prevention bytes');
assert(main.includes('isRangeBitActive'), 'binary highlighting should support non-contiguous field ranges');
assert(main.includes('getClickedFieldRange'), 'binary highlighting should use DOM ranges for synthetic tree nodes');
assert(main.includes('range.coding'), 'field rows should show whether highlighted bits are fixed-width or Exp-Golomb coded');
assert(main.includes('formatCodingText'), 'field rows should explain Exp-Golomb codewords separately from decoded values');
assert(main.includes('codeword'), 'Exp-Golomb fields should show the highlighted codeword');
assert(main.includes('isFileInputActivator'), 'drop-zone click handler should ignore clicks already handled by the file input label');
assert(main.includes('label[for="file-input"], #file-input'), 'file picker guard should cover the label and the input itself');
assert(main.includes("fileInput.value = ''"), 'file input should reset before opening so selecting the same file triggers parsing again');

console.log('main UI text assertions passed');
