const assert = require('assert');
const fs = require('fs');

const html = fs.readFileSync('index.html', 'utf8');
const main = fs.readFileSync('main.js', 'utf8');

const tidHeaderCount = (html.match(/class="tid-col" title="Temporal ID"><abbr title="Temporal ID">TID<\/abbr>/g) || []).length;
assert.strictEqual(tidHeaderCount, 2, 'NAL and frames tables should mark TID headers with a dedicated column class');
assert(html.includes('<th class="tid-col" title="Temporal ID"><abbr title="Temporal ID">TID</abbr></th>'), 'NAL table should mark TID header with a dedicated column class');
assert(main.includes('<td class="tid-col">'), 'NAL table should mark TID values with the same column class as the header');
assert(!html.includes('<colgroup>'), 'NAL table should not use colgroup for hidden codec columns');
assert(html.includes('<th id="nal-codec-header" class="codec-col">Ref IDC</th>'), 'NAL table should have one codec-specific header');
assert(!html.includes('class="col-h264"'), 'NAL table should not keep a hidden H.264 column');
assert(!html.includes('class="col-h265"'), 'NAL table should not keep a hidden H.265 column');
assert(main.includes('nalCodecHeader.textContent'), 'NAL table should rename the single codec column per codec');
assert(main.includes('<td class="codec-col">'), 'NAL rows should render one codec-specific value column');
assert(html.indexOf('<th>Frame</th>') < html.indexOf('<th>起始码</th>'), 'NAL table should show Frame before start code');
assert(main.indexOf('frame-pill') < main.indexOf('${startCodeType}</td>'), 'NAL rows should render Frame before start code');
assert(main.includes('getNALDisplayName'), 'NAL name cells should use compact display names');
assert(main.includes('title="${escapeHtml(nal.type_name)}"'), 'NAL name cells should keep the full name in a tooltip');
assert(main.includes('Showing bytes'), 'binary truncation note should explain that it is a preview window');
assert(main.includes('Showing all'), 'binary note should also explain when the full NAL is visible');
assert(main.includes('toLocaleString()'), 'binary truncation note should format large byte counts');
assert(main.includes('data-search-text'), 'NAL rows should carry normalized search text');
assert(main.includes('data-frame-type'), 'NAL rows should expose frame type for exact I/P/B filtering');
assert(main.includes('getFrameTypeSearchQuery'), 'NAL filter should special-case exact I/P/B frame type queries');
assert(main.includes('buildNALSearchText'), 'NAL search should be built from structured fields');
assert(main.includes('frame ${frameType.toLowerCase()}'), 'NAL search text should include frame I/P/B tokens');
assert(main.includes('frame-idr'), 'NAL frame pill should have a distinct IDR style');
assert(main.includes("frameType === 'IDR'"), 'NAL frame display should distinguish IDR from regular I frames');
assert(main.includes('idrFrames'), 'summary should render IDR counts separately');
assert(main.includes('field-clickable'), 'clickable field rows should have an explicit class');
assert(main.includes('field-static'), 'static field rows should have an explicit class');
assert(main.includes('buildNALFieldTree'), 'Selected NAL fields should be rendered from a tree model');
assert(main.includes('renderFieldTreeNode'), 'Selected NAL tree should render nested nodes');
assert(main.includes('field-tree-node'), 'Selected NAL tree should use collapsible node markup');
assert(main.includes('field-tree-toggle'), 'Selected NAL tree nodes should have an explicit toggle area');
assert(main.includes('field-tree-children'), 'Selected NAL tree should group nested child rows');
assert(main.includes('data-field-path'), 'clickable tree leaves should keep field paths for bit highlighting');
assert(main.includes('FLAG_GROUP_RULES'), 'Selected NAL tree should group conditional fields under their controlling flags');
assert(main.includes('groupConditionalFieldNodes'), 'Selected NAL tree should normalize flag-controlled subtrees');
assert(main.includes('SYNTHETIC_GROUP_RULES'), 'Selected NAL tree should provide synthetic syntax-section groups');
assert(main.includes('PPS Extension'), 'PPS extension fields should be grouped under an expandable PPS Extension node');
assert(main.includes('bitstream_restriction_flag'), 'VUI bitstream restriction fields should be grouped under bitstream_restriction_flag');
assert(main.includes('vui_timing_info_present_flag'), 'H.265 VUI timing fields should be grouped under vui_timing_info_present_flag');
assert(main.includes('vui_hrd_parameters_present_flag'), 'H.265 VUI HRD fields should be grouped under vui_hrd_parameters_present_flag');
assert(main.includes('vps_timing_info_present_flag'), 'H.265 VPS timing fields should be grouped under vps_timing_info_present_flag');
assert(main.includes('pps_extension_present_flag'), 'H.265 PPS extension fields should be grouped under pps_extension_present_flag');
assert(main.includes('sps_extension_present_flag'), 'H.265 SPS extension fields should be grouped under sps_extension_present_flag');
assert(main.includes('pps_scc_extension_flag'), 'H.265 PPS SCC extension fields should be grouped under pps_scc_extension_flag');
assert(main.includes('sps_scc_extension_flag'), 'H.265 SPS SCC extension fields should be grouped under sps_scc_extension_flag');
assert(main.includes('frame_cropping_flag'), 'SPS crop offsets should be grouped under frame_cropping_flag');
assert(main.includes('field-tree-toggle') && main.includes('data-field-path'), 'clickable tree group nodes should keep field paths for bit highlighting');
assert(main.includes('assignAggregateFieldRanges'), 'tree parent nodes should receive aggregate bit ranges from clickable children');
assert(!main.includes('node.range.coding'), 'aggregate field range creation must not dereference an empty node.range');
assert(main.includes('data-field-start-bit'), 'clickable field nodes should carry bit ranges in the DOM');
assert(main.includes('data-field-segments'), 'clickable field nodes should carry segmented bit ranges for H.265 emulation-prevention bytes');
assert(main.includes('isRangeBitActive'), 'binary highlighting should support non-contiguous field ranges');
assert(main.includes('getClickedFieldRange'), 'binary highlighting should use DOM ranges for synthetic tree nodes');
assert(main.includes('range.coding'), 'field rows should show whether highlighted bits are fixed-width or Exp-Golomb coded');
assert(main.includes('formatCodingText'), 'field rows should explain Exp-Golomb codewords separately from decoded values');
assert(main.includes('codeword'), 'Exp-Golomb fields should show the highlighted codeword');
assert(main.includes('isFileInputActivator'), 'drop-zone click handler should ignore clicks already handled by the file input label');
assert(main.includes('label[for="file-input"], #file-input'), 'file picker guard should cover the label and the input itself');
assert(main.includes("fileInput.value = ''"), 'file input should reset before opening so selecting the same file triggers parsing again');

console.log('main UI text assertions passed');
